### ISSUE TITLE
FAILED: prroi_pooling_gpu.o

### ISSUE THREAD

**Issue by wangjun2022** [VISION-SJTU/USOT#18]
When I run the tset " python -u ./scripts/test_usot.py --dataset VOT2018 --resume ./var/snapshot/USOT_star.pth"，The following error will appear：
Using C:\Users\wj\AppData\Local\torch_extensions\torch_extensions\Cache as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\wj\AppData\Local\torch_extensions\torch_extensions\Cache\_prroi_pooling\build.ninja...
Building extension module _prroi_pooling...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] cl /showIncludes -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -ID:\anaconda3\envs\usot2\lib\site-packages\torch\include -ID:\anaconda3\envs\usot2\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda3\envs\usot2\lib\site-packages\torch\include\TH -ID:\anaconda3\envs\usot2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -ID:\anaconda3\envs\usot2\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -c E:\object_tracking\unsupervised_object_tracking\USOT-main\lib\models\prroi_pool\src\prroi_pooling_gpu.c /Foprroi_pooling_gpu.o
FAILED: prroi_pooling_gpu.o
cl /showIncludes -DTORCH_EXTENSION_NAME=_prroi_pooling -DTORCH_API_INCLUDE_EXTENSION_H -ID:\anaconda3\envs\usot2\lib\site-packages\torch\include -ID:\anaconda3\envs\usot2\lib\site-packages\torch\include\torch\csrc\api\include -ID:\anaconda3\envs\usot2\lib\site-packages\torch\include\TH -ID:\anaconda3\envs\usot2\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -ID:\anaconda3\envs\usot2\Include -D_GLIBCXX_USE_CXX11_ABI=0 /MD /wd4819 /wd4251 /wd4244 /wd4267 /wd4275 /wd4018 /wd4190 /EHsc -c E:\object_tracking\unsupervised_object_tracking\USOT-main\lib\models\prroi_pool\src\prroi_pooling_gpu.c /Foprroi_pooling_gpu.o
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.32.31332 版
版权所有(C) Microsoft Corporation。保留所有权利。

注意: 包含文件:  D:\Windows Kits\10\include\10.0.19041.0\ucrt\math.h
注意: 包含文件:   D:\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_math.h
注意: 包含文件:    D:\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt.h
注意: 包含文件:     D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vcruntime.h
注意: 包含文件:      D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\sal.h
注意: 包含文件:       D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\concurrencysal.h
注意: 包含文件:      D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\vadefs.h
注意: 包含文件:  D:\anaconda3\envs\usot2\lib\site-packages\torch\include\torch/extension.h
注意: 包含文件:   D:\anaconda3\envs\usot2\lib\site-packages\torch\include\torch\csrc\api\include\torch/all.h
注意: 包含文件:    D:\anaconda3\envs\usot2\lib\site-packages\torch\include\torch\csrc\api\include\torch/cuda.h
注意: 包含文件:     D:\anaconda3\envs\usot2\lib\site-packages\torch\include\torch/csrc/WindowsTorchApiMacro.h
注意: 包含文件:      D:\anaconda3\envs\usot2\lib\site-packages\torch\include\c10/macros/Export.h
注意: 包含文件:       D:\anaconda3\envs\usot2\lib\site-packages\torch\include\c10/macros/cmake_macros.h
注意: 包含文件:     D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\cstdint
注意: 包含文件:      D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\yvals_core.h
D:\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\yvals_core.h(23): fatal error C1189: #error:  STL1003: Unexpected compiler, expected C++ compiler.
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "D:\anaconda3\envs\usot2\lib\site-packages\torch\utils\cpp_extension.py", line 1540, in _run_ninja_build
    env=env)
  File "D:\anaconda3\envs\usot2\lib\subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./scripts/test_usot.py", line 167, in <module>
    main()
  File "./scripts/test_usot.py", line 163, in main
    track(tracker, net, dataset[video], args)
  File "./scripts/test_usot.py", line 92, in track
    state = tracker.init(im, target_pos, target_sz, net)
  File ".\lib\tracker\usot_tracker.py", line 72, in init
    net.template(z.cuda(), template_bbox=template_bbox)
  File ".\lib\models\models.py", line 177, in template
    _, self.zf = self.neck(self.zf, crop=True, pr_pool=self.pr_pool, bbox=template_bbox)
  File "D:\anaconda3\envs\usot2\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File ".\lib\models\connect.py", line 313, in forward
    xf_pr = self.prpooling(x_ori, bbox)
  File "D:\anaconda3\envs\usot2\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File ".\lib\models\prroi_pool\prroi_pool.py", line 28, in forward
    return prroi_pool2d(features, rois, self.pooled_height, self.pooled_width, self.spatial_scale)
  File ".\lib\models\prroi_pool\functional.py", line 44, in forward
    _prroi_pooling = _import_prroi_pooling()
  File ".\lib\models\prroi_pool\functional.py", line 33, in _import_prroi_pooling
    verbose=True
  File "D:\anaconda3\envs\usot2\lib\site-packages\torch\utils\cpp_extension.py", line 998, in load
    keep_intermediates=keep_intermediates)
  File "D:\anaconda3\envs\usot2\lib\site-packages\torch\utils\cpp_extension.py", line 1203, in _jit_compile
    with_cuda=with_cuda)
  File "D:\anaconda3\envs\usot2\lib\site-packages\torch\utils\cpp_extension.py", line 1301, in _write_ninja_file_and_build_library
    error_prefix="Error building extension '{}'".format(name))
  File "D:\anaconda3\envs\usot2\lib\site-packages\torch\utils\cpp_extension.py", line 1556, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension '_prroi_pooling'

**Comment by zhengjilai** [comment]
This error happens if you fail to compile the Precise RoI Pooling library (./lib/models/prroi_pool).
Please refer to #2 for more details. I recommend running the repo with Linux instead of Windows.
